spring:
  redis:
    database: 0
    host: 192.168.146.135
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
server:
  port: 8080
